/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SetFileTimesOptions {
  path: string
  btime?: string
  mtime?: string
  atime?: string
}
export interface SetFileTimesResult {
  error?: string
}
export interface FileTimesResult {
  error?: string
  btime?: string
  mtime?: string
  atime?: string
}
export declare function setFileTimes(options: SetFileTimesOptions): SetFileTimesResult
export declare function getFileTimes(path: string): FileTimesResult
